import { ReactComponent as loading } from 'images/svg/loading-svgrepo-com.svg';
export const catalog_sceleton = {
  catalog: [
    {
      _id: '6606b92c77c67f4768dce579',
      uuid: '1ee3b73a-3cef-11ee-bac0-244bfeb81e10',
      title: 'Socks Staff white (p. 39-42)',
      article: 'WQ0529',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 39-42.<br/>- brand logo on the foot.<br/><br/>Color:<br/>- white.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/11/936822e64a2a4fcc81dbb1a313008b88.jpeg, https://static.staff-clothes.com/uploads/media/image_product/0003/11/9ae5e248826a4fd098664dde280bbb8f.jpeg',
      creation_datetime: '2023-08-28 15:20:28',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'rate',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 8.6,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce577',
      uuid: '4d04e853-3cef-11ee-bac0-244bfeb81e10',
      title: 'Staff beige socks (years 43-46)',
      article: 'WQ0531',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 43-46.<br/>- brand logo on the foot.<br/><br/>Color:<br/>- beige.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/11/e80d725a13cb4f358c736bbfdbe8e3f7.jpeg, https://static.staff-clothes.com/uploads/media/image_product/0003/11/cf213e4a6f5d4fd0915e066a38630c2a.jpeg',
      creation_datetime: '2023-08-28 15:20:59',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'discount',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 8.7,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce595',
      uuid: 'be3040ac-376c-11ee-bac0-244bfeb81e10',
      title: 'Staff black socks, 43-46',
      article: 'WQ0513',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 43-46;<br/>- brand logo on the foot.<br/><br/>Color:<br/>- black.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/10/555eac44fa934fe780e37803a4b2067c.jpeg, https://static.staff-clothes.com/uploads/media/image_product/0003/10/030846e526194f2bbeee6650341fb8e1.jpeg',
      creation_datetime: '2023-08-18 15:57:24',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'rate',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 6.1,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce57b',
      uuid: 'a26770db-3c13-11ee-bac0-244bfeb81e10',
      title: 'Socks Staff white (p. 43-46)',
      article: 'WQ0522',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 43-46.<br/>- brand logo on the foot.<br/><br/>Color:<br/>- white.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/11/7a49c778ced34fb29155d81083c54cd8.jpeg, https://static.staff-clothes.com/uploads/media/image_product/0003/11/cc40d25f041a4fb2aff6cf8ea3360569.jpeg',
      creation_datetime: '2023-08-28 15:19:33',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'discount',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 6.4,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce596',
      uuid: '903dab79-3749-11ee-bac0-244bfeb81e10',
      title: 'Staff gray socks, 43-46',
      article: 'WQ0508',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 43-46;<br/>- brand logo on the foot.<br/><br/>Color:<br/>- gray.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/10/703dbf550e034f1195eb5b45018e797b.jpeg, https://static.staff-clothes.com/uploads/media/image_product/0003/10/ea633ce8d9594fd99560b8fd5507ee62.jpeg',
      creation_datetime: '2023-08-18 15:55:29',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'new',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 6,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce57a',
      uuid: '0640d58b-3cef-11ee-bac0-244bfeb81e10',
      title: 'Socks Staff gray (p. 39-42)',
      article: 'WQ0528',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 39-42.<br/>- brand logo on the foot.<br/><br/>Color:<br/>- gray.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/11/2943d1a6c4734f01b76eb0b60eed5c5f.jpeg',
      creation_datetime: '2023-08-28 15:20:04',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: '',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 9.3,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce578',
      uuid: '3dec72f6-3cef-11ee-bac0-244bfeb81e10',
      title: 'Socks Staff beige (p. 39-42)',
      article: 'WQ0530',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 39-42.<br/>- brand logo on the foot.<br/><br/>Color:<br/>- beige.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images: '',
      creation_datetime: '2023-08-28 15:20:50',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'rate',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 9.7,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce675',
      uuid: 'f5020344-ce12-11ed-bab9-244bfeb81e10',
      title: "Women's socks Staff black",
      article: 'WQ0428',
      description:
        'Choose your color and easily complete the look with socks from Staff. The model will emphasize your style, please with its quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br/ />- type: invisible;<br/>- size: 36-39;<br/>- brand logo on the foot.<br/><br/>Color:<br/>- black.<br />< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°C, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without using artificial drying .',
      man_women: "Women's",
      category: 'Accessories',
      product: 'Belts, Socks, glasses, gloves',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0002/91/a2f4c4154c184fde90051dc90f5c6c8e.jpeg',
      creation_datetime: '2023-04-05 17:05:58',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'new',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 9.1,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce687',
      uuid: '54926bf6-c3e7-11ed-bab8-244bfeb81e10',
      title: 'Socks Staff gray & white',
      article: 'WQ0424',
      description:
        'Details are very important in every image. Staff socks will emphasize your style, please you with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity. There is an additional ball of cotton on the foot for more reliable insulation.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details:<br/>- type: short;<br/>- size: 40-45.<br/><br/>Color:<br/>- gray/white.<br/><br/>Care:<br / >- washing in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without using artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0002/89/26e5aa5a7e184f59a8497b80f8b37cc5.jpeg',
      creation_datetime: '2023-03-22 17:20:04',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'new',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 8.5,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce676',
      uuid: 'bd5b9874-ce12-11ed-bab9-244bfeb81e10',
      title: "Women's socks Staff white",
      article: 'WQ0427',
      description:
        'Choose your color and easily complete the look with socks from Staff. The model will emphasize your style, please with its quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br/ />- type: invisible;<br/>- size: 36-39;<br/>- brand logo on the foot.<br/><br/>Color:<br/>- white.<br />< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°C, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without using artificial drying .',
      man_women: "Women's",
      category: 'Accessories',
      product: 'Belts, Socks, glasses, gloves',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0002/91/b333971a718d4f98b1bf4ca5492411fa.jpeg',
      creation_datetime: '2023-04-05 17:02:39',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'rate',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 9.1,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce5b3',
      uuid: '2075e3bd-32bc-11ee-bac0-244bfeb81e10',
      title: 'Staff black socks, 39-42',
      article: 'WQ0503',
      description:
        'Details are very important in every image. Socks will emphasize your style, please with their quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane.<br/><br/>Details: <br />- type: short;<br/>- size: 39-42.<br/>- brand logo on the foot.<br/><br/>Color:<br/>- black.<br/ >< br/>Care:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without artificial drying.',
      man_women: "Men's",
      category: 'Accessories',
      product: 'Socks',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/08/74c14cea2c124fa18142df42a4a4cfbf.jpeg',
      creation_datetime: '2023-08-10 17:00:24',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: 'rate',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 6.8,
      __v: 0,
    },
    {
      _id: '6606b92c77c67f4768dce127',
      uuid: 'fb6bb0ac-cfc0-11ee-bac7-244bfeb81e10',
      title: "Women's socks Staff light blue",
      article: 'WQ0554',
      description:
        'Choose your color and easily complete the look with socks from Staff. The model will emphasize your style, will please you with its quality, good density and resistance to frequent washing. The soft fabric is supplemented with elastane and polyamide for greater strength and elasticity.<br/><br/>Material:<br/>85% cotton, 10% polyamide, 5% elastane. <br/>- type: short;<br/>- size: 36-39;<br/>- brand logo on the foot.<br/><br/>Color:<br/>- blue.<br/ ><br/>Overview:<br/>- wash in normal mode at a temperature not higher than 30°С, without spinning;<br/>- bleaching is prohibited;<br/>- hang dry, without using artificial drying.',
      man_women: "Women's",
      category: 'Accessories',
      product: 'Belts, Socks, glasses, gloves',
      mainImage: loading,
      images:
        'https://static.staff-clothes.com/uploads/media/image_product/0003/38/c53395a27a904fe2b9074064fd62e385.jpeg, https://static.staff-clothes.com/uploads/media/image_product/0003/38/fbbe3898a9c14f04a2b1d8e9e1600042.jpeg',
      creation_datetime: '2024-03-11 18:50:44',
      sizes: 'Universal',
      price_ua: 40,
      newPrice_ua: 50,
      oldPrice_ua: 58,
      price_usd: 1.05,
      newPrice_usd: 1.32,
      oldPrice_usd: 1.53,
      price_euro: 0.95,
      newPrice_euro: 1.19,
      oldPrice_euro: 1.38,
      status: '',
      discount_ua: 8,
      discount_usd: 0.21,
      discount_euro: 0.19,
      rate: 9.9,
      __v: 0,
    },
  ],
  total: 1721,
};
